name: Example Workflow
on: 
    workflow_dispatch:
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./composite-test.yml
        with:
          dummy-token: ${{ secrets.DUMMY_TOKEN }}